spring.application.name=solarispower
server.port=8080


# Configuração da OpenAI no Spring AI
spring.ai.openai.api-key=SUA_CHAVE_OPENAI_AQUI
spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.openai.chat.options.temperature=0.7

mercadopago.access_token=TEST-7751286980864329-052313-3bb1b2989a05299322a6714e008a7789-651291232    


